require("dotenv").config();

const bcrypt = require("bcryptjs");
const pool = require("./config/db");

const PASSWORD = "Test@123";

const startups = [
    {
        email: "nihar9817@gmail.com",
        name: "Finora",
        startup: {
            name: "Finora",
            tagline: "Smarter financial decisions for growing businesses",
            industry: "FinTech",
            sub_industry: "Business Finance",
            founded_year: 2023,
            location: "Bengaluru, India",
            website: "https://finora.example.com",
            description: "Finora provides an intelligent financial management platform that helps small businesses track cash flow, manage expenses and make better financial decisions.",
            problem: "Small businesses often rely on spreadsheets and disconnected financial tools.",
            solution: "A unified platform for cash-flow monitoring, expense management and financial insights.",
            business_model: "B2B SaaS subscription",
            target_market: "Small and medium businesses",
            competitors: "Razorpay, Zoho Books, Clear",
            competitive_advantage: "Real-time financial intelligence designed specifically for growing SMEs.",
            stage: "Growth",
            team_size: 18,
            revenue: 4200000,
            monthly_revenue: 450000,
            revenue_growth: 18.5,
            customers: 310,
            active_users: 1250,
            monthly_burn: 280000,
            runway: 24,
            gross_margin: 76,
            cac: 8500,
            ltv: 145000,
            funding_stage: "Seed",
            funding_required: 12000000,
            amount_raised: 6500000,
            valuation: 55000000,
            equity_offered: 12,
            minimum_investment: 500000
        }
    },
    {
        email: "sagar1477.be24@chitkarauniversity.edu.in",
        name: "AgriPulse",
        startup: {
            name: "AgriPulse",
            tagline: "Data-driven farming for every acre",
            industry: "AgriTech",
            sub_industry: "Precision Agriculture",
            founded_year: 2022,
            location: "Pune, India",
            website: "https://agripulse.example.com",
            description: "AgriPulse combines farm data, weather intelligence and crop analytics to help farmers improve productivity.",
            problem: "Farmers lack affordable and timely information about crop health and irrigation.",
            solution: "A digital farming assistant that provides crop recommendations and field-level insights.",
            business_model: "Subscription and B2B partnerships",
            target_market: "Farmers, FPOs and agricultural enterprises",
            competitors: "DeHaat, AgroStar, CropIn",
            competitive_advantage: "Affordable field-level analytics designed for small farms.",
            stage: "Early Growth",
            team_size: 24,
            revenue: 6800000,
            monthly_revenue: 610000,
            revenue_growth: 24.2,
            customers: 1850,
            active_users: 6200,
            monthly_burn: 410000,
            runway: 20,
            gross_margin: 69,
            cac: 3200,
            ltv: 82000,
            funding_stage: "Seed",
            funding_required: 18000000,
            amount_raised: 9000000,
            valuation: 72000000,
            equity_offered: 15,
            minimum_investment: 750000
        }
    },
    {
        email: "saksham14831477.be24@chitkarauniversity.edu.in",
        name: "MedNexa",
        startup: {
            name: "MedNexa",
            tagline: "Connected healthcare for everyday India",
            industry: "HealthTech",
            sub_industry: "Digital Healthcare",
            founded_year: 2024,
            location: "Hyderabad, India",
            website: "https://mednexa.example.com",
            description: "MedNexa connects patients with clinics, diagnostic services and digital health records through one platform.",
            problem: "Patients struggle to manage appointments, reports and medical information across different providers.",
            solution: "A unified digital healthcare coordination platform.",
            business_model: "B2B2C platform fees",
            target_market: "Urban and semi-urban healthcare consumers",
            competitors: "Practo, Apollo 24/7, Tata 1mg",
            competitive_advantage: "Integrated clinic workflow combined with patient health records.",
            stage: "Pre-Series A",
            team_size: 31,
            revenue: 9200000,
            monthly_revenue: 830000,
            revenue_growth: 31.4,
            customers: 740,
            active_users: 15800,
            monthly_burn: 720000,
            runway: 18,
            gross_margin: 64,
            cac: 6100,
            ltv: 97000,
            funding_stage: "Pre-Series A",
            funding_required: 30000000,
            amount_raised: 14500000,
            valuation: 120000000,
            equity_offered: 14,
            minimum_investment: 1000000
        }
    },
    {
        email: "lucky1317be24@chitkarauniversity.edu.in",
        name: "SkillForge",
        startup: {
            name: "SkillForge",
            tagline: "Career skills built around real industry needs",
            industry: "EdTech",
            sub_industry: "Professional Learning",
            founded_year: 2022,
            location: "Delhi, India",
            website: "https://skillforge.example.com",
            description: "SkillForge provides practical technology and business learning programs focused on employability.",
            problem: "Students often complete courses without developing job-ready practical skills.",
            solution: "Project-based learning with industry mentors and skill assessments.",
            business_model: "Course subscriptions and institutional licensing",
            target_market: "College students and early-career professionals",
            competitors: "upGrad, Scaler, Coursera",
            competitive_advantage: "Hands-on projects and structured industry mentorship.",
            stage: "Growth",
            team_size: 27,
            revenue: 11500000,
            monthly_revenue: 970000,
            revenue_growth: 21.7,
            customers: 4200,
            active_users: 18700,
            monthly_burn: 680000,
            runway: 22,
            gross_margin: 72,
            cac: 2800,
            ltv: 54000,
            funding_stage: "Seed",
            funding_required: 22000000,
            amount_raised: 11000000,
            valuation: 90000000,
            equity_offered: 13,
            minimum_investment: 750000
        }
    },
    {
        email: "sanchit1499.be24@chitkarauniversity.edu.in",
        name: "LogiFleet",
        startup: {
            name: "LogiFleet",
            tagline: "Intelligent logistics for modern businesses",
            industry: "Logistics",
            sub_industry: "Fleet Management",
            founded_year: 2021,
            location: "Gurugram, India",
            website: "https://logifleet.example.com",
            description: "LogiFleet helps logistics operators monitor fleets, optimize routes and reduce operational costs.",
            problem: "Fleet operators lose money because of inefficient routes and poor vehicle utilization.",
            solution: "Fleet analytics and route optimization software.",
            business_model: "B2B SaaS",
            target_market: "Logistics companies and delivery fleets",
            competitors: "Locus, FarEye, Shipsy",
            competitive_advantage: "Predictive fleet analytics with automated route optimization.",
            stage: "Growth",
            team_size: 42,
            revenue: 18500000,
            monthly_revenue: 1580000,
            revenue_growth: 27.8,
            customers: 280,
            active_users: 2100,
            monthly_burn: 1050000,
            runway: 19,
            gross_margin: 81,
            cac: 42000,
            ltv: 680000,
            funding_stage: "Series A",
            funding_required: 60000000,
            amount_raised: 35000000,
            valuation: 280000000,
            equity_offered: 11,
            minimum_investment: 2500000
        }
    },
    {
        email: "gagan1210.be24@chitkarauniversity.edu.in",
        name: "BuildNest",
        startup: {
            name: "BuildNest",
            tagline: "Making construction procurement effortless",
            industry: "ConTech",
            sub_industry: "Construction Procurement",
            founded_year: 2023,
            location: "Ahmedabad, India",
            website: "https://buildnest.example.com",
            description: "BuildNest is a procurement platform connecting construction companies with verified material suppliers.",
            problem: "Construction companies face fragmented suppliers, uncertain pricing and delayed procurement.",
            solution: "Digital sourcing, quotation comparison and supplier management.",
            business_model: "Marketplace commission",
            target_market: "Contractors and construction companies",
            competitors: "Infra.Market, Moglix",
            competitive_advantage: "Verified local suppliers and transparent price comparison.",
            stage: "Early Growth",
            team_size: 22,
            revenue: 7300000,
            monthly_revenue: 640000,
            revenue_growth: 29.1,
            customers: 540,
            active_users: 1300,
            monthly_burn: 390000,
            runway: 21,
            gross_margin: 38,
            cac: 7200,
            ltv: 118000,
            funding_stage: "Seed",
            funding_required: 16000000,
            amount_raised: 7000000,
            valuation: 64000000,
            equity_offered: 14,
            minimum_investment: 500000
        }
    },
    {
        email: "gargi1211.be24@chitkarauniversity.edu.in",
        name: "GreenGrid",
        startup: {
            name: "GreenGrid",
            tagline: "Making clean energy simpler for businesses",
            industry: "CleanTech",
            sub_industry: "Energy Management",
            founded_year: 2022,
            location: "Jaipur, India",
            website: "https://greengrid.example.com",
            description: "GreenGrid provides energy monitoring and optimization solutions for commercial buildings.",
            problem: "Businesses lack visibility into energy waste and inefficient equipment.",
            solution: "Smart energy monitoring with actionable consumption recommendations.",
            business_model: "Hardware plus SaaS",
            target_market: "Commercial buildings and industrial facilities",
            competitors: "Schneider Electric, Honeywell",
            competitive_advantage: "Affordable monitoring designed for mid-sized facilities.",
            stage: "Growth",
            team_size: 36,
            revenue: 13200000,
            monthly_revenue: 1120000,
            revenue_growth: 22.9,
            customers: 190,
            active_users: 860,
            monthly_burn: 780000,
            runway: 17,
            gross_margin: 61,
            cac: 48000,
            ltv: 520000,
            funding_stage: "Seed",
            funding_required: 28000000,
            amount_raised: 13000000,
            valuation: 110000000,
            equity_offered: 12,
            minimum_investment: 1000000
        }
    },
    {
        email: "pranav1421.be24@chitkarauniversity.edu.in",
        name: "CyberShieldX",
        startup: {
            name: "CyberShieldX",
            tagline: "Security intelligence for growing companies",
            industry: "Cybersecurity",
            sub_industry: "Cloud Security",
            founded_year: 2024,
            location: "Chennai, India",
            website: "https://cybershieldx.example.com",
            description: "CyberShieldX helps startups continuously monitor cloud infrastructure and identify security risks.",
            problem: "Small companies lack affordable security monitoring and specialist teams.",
            solution: "Automated cloud security monitoring and risk alerts.",
            business_model: "SaaS subscription",
            target_market: "Startups and mid-sized technology companies",
            competitors: "Cloudflare, Wiz, Palo Alto Networks",
            competitive_advantage: "Simple deployment and affordable security monitoring.",
            stage: "MVP",
            team_size: 14,
            revenue: 2100000,
            monthly_revenue: 190000,
            revenue_growth: 35.6,
            customers: 78,
            active_users: 340,
            monthly_burn: 260000,
            runway: 16,
            gross_margin: 88,
            cac: 18000,
            ltv: 310000,
            funding_stage: "Pre-Seed",
            funding_required: 10000000,
            amount_raised: 2500000,
            valuation: 40000000,
            equity_offered: 15,
            minimum_investment: 500000
        }
    },
    {
        email: "nikhil1377.be24@chitkarauniversity.edu.in",
        name: "FoodLoop",
        startup: {
            name: "FoodLoop",
            tagline: "Better food distribution, less waste",
            industry: "FoodTech",
            sub_industry: "Food Supply Chain",
            founded_year: 2021,
            location: "Mumbai, India",
            website: "https://foodloop.example.com",
            description: "FoodLoop helps restaurants and retailers source surplus and fresh inventory efficiently.",
            problem: "Large amounts of food are wasted because demand and supply are poorly coordinated.",
            solution: "Inventory intelligence and marketplace-based food redistribution.",
            business_model: "Transaction commission",
            target_market: "Restaurants, retailers and food suppliers",
            competitors: "Zomato Hyperpure, Udaan",
            competitive_advantage: "Demand forecasting combined with surplus redistribution.",
            stage: "Growth",
            team_size: 39,
            revenue: 16400000,
            monthly_revenue: 1410000,
            revenue_growth: 19.8,
            customers: 620,
            active_users: 3400,
            monthly_burn: 890000,
            runway: 23,
            gross_margin: 44,
            cac: 9600,
            ltv: 156000,
            funding_stage: "Series A",
            funding_required: 45000000,
            amount_raised: 26000000,
            valuation: 210000000,
            equity_offered: 10,
            minimum_investment: 2000000
        }
    },
    {
        email: "nikita1378.be24@chitkarauniversity.edu.in",
        name: "TravelMint",
        startup: {
            name: "TravelMint",
            tagline: "Personalized travel planning made simple",
            industry: "TravelTech",
            sub_industry: "Travel Planning",
            founded_year: 2023,
            location: "Goa, India",
            website: "https://travelmint.example.com",
            description: "TravelMint helps travelers plan personalized trips based on budgets, interests and available time.",
            problem: "Travel planning requires switching between multiple websites and applications.",
            solution: "One platform for personalized itineraries, bookings and local experiences.",
            business_model: "Booking commissions and premium subscriptions",
            target_market: "Young professionals and families",
            competitors: "MakeMyTrip, Booking.com, TripAdvisor",
            competitive_advantage: "Personalized itinerary engine with local experience discovery.",
            stage: "Early Growth",
            team_size: 19,
            revenue: 5600000,
            monthly_revenue: 490000,
            revenue_growth: 26.4,
            customers: 1700,
            active_users: 9200,
            monthly_burn: 370000,
            runway: 18,
            gross_margin: 57,
            cac: 1900,
            ltv: 27000,
            funding_stage: "Seed",
            funding_required: 14000000,
            amount_raised: 6000000,
            valuation: 58000000,
            equity_offered: 13,
            minimum_investment: 500000
        }
    },
    {
        email: "nikhil1475.be24@chitkarauniversity.edu.in",
        name: "RetailNova",
        startup: {
            name: "RetailNova",
            tagline: "Digital intelligence for neighborhood retailers",
            industry: "RetailTech",
            sub_industry: "Retail Analytics",
            founded_year: 2022,
            location: "Kolkata, India",
            website: "https://retailnova.example.com",
            description: "RetailNova gives independent retailers tools for inventory management, sales analytics and customer engagement.",
            problem: "Small retailers lack affordable technology to understand their customers and inventory.",
            solution: "Simple retail management software with analytics and loyalty features.",
            business_model: "SaaS subscription",
            target_market: "Independent retailers and local chains",
            competitors: "Zoho, Shopify, GoFrugal",
            competitive_advantage: "Designed specifically for small Indian retailers.",
            stage: "Growth",
            team_size: 29,
            revenue: 8700000,
            monthly_revenue: 750000,
            revenue_growth: 23.6,
            customers: 2100,
            active_users: 7800,
            monthly_burn: 520000,
            runway: 24,
            gross_margin: 79,
            cac: 2900,
            ltv: 74000,
            funding_stage: "Seed",
            funding_required: 20000000,
            amount_raised: 9500000,
            valuation: 82000000,
            equity_offered: 12,
            minimum_investment: 750000
        }
    },
    {
        email: "saima1480.be24@chitkarauniversity.edu.in",
        name: "WaterWise",
        startup: {
            name: "WaterWise",
            tagline: "Smarter water management for every city",
            industry: "ClimateTech",
            sub_industry: "Water Management",
            founded_year: 2021,
            location: "Bengaluru, India",
            website: "https://waterwise.example.com",
            description: "WaterWise provides monitoring systems that help buildings and institutions detect leaks and reduce water consumption.",
            problem: "Water leakage and inefficient consumption create major avoidable losses.",
            solution: "IoT sensors and analytics for water monitoring.",
            business_model: "Hardware subscription and SaaS",
            target_market: "Apartments, hotels and institutions",
            competitors: "Wint, Smart Water Networks",
            competitive_advantage: "Low-cost sensors combined with centralized consumption analytics.",
            stage: "Growth",
            team_size: 33,
            revenue: 10100000,
            monthly_revenue: 870000,
            revenue_growth: 20.3,
            customers: 340,
            active_users: 1200,
            monthly_burn: 620000,
            runway: 20,
            gross_margin: 63,
            cac: 15500,
            ltv: 210000,
            funding_stage: "Seed",
            funding_required: 24000000,
            amount_raised: 10500000,
            valuation: 95000000,
            equity_offered: 13,
            minimum_investment: 750000
        }
    },
    {
        email: "mahskas.sharma2005@gmail.com",
        name: "LegalEase",
        startup: {
            name: "LegalEase",
            tagline: "Legal operations without the complexity",
            industry: "LegalTech",
            sub_industry: "Legal Automation",
            founded_year: 2023,
            location: "Noida, India",
            website: "https://legalease.example.com",
            description: "LegalEase helps startups manage contracts, compliance tasks and legal documents from one workspace.",
            problem: "Early-stage companies struggle to organize legal documents and compliance deadlines.",
            solution: "Digital legal workspace with document tracking and compliance workflows.",
            business_model: "SaaS subscription",
            target_market: "Startups and small businesses",
            competitors: "SpotDraft, DocuSign, Vakilsearch",
            competitive_advantage: "Affordable legal workflow automation for startups.",
            stage: "MVP",
            team_size: 12,
            revenue: 1800000,
            monthly_revenue: 160000,
            revenue_growth: 32.2,
            customers: 115,
            active_users: 480,
            monthly_burn: 220000,
            runway: 15,
            gross_margin: 84,
            cac: 6700,
            ltv: 118000,
            funding_stage: "Pre-Seed",
            funding_required: 8000000,
            amount_raised: 1800000,
            valuation: 32000000,
            equity_offered: 16,
            minimum_investment: 300000
        }
    },
    {
        email: "mahskas.sharma2005ss@gmail.com",
        name: "MediRoute",
        startup: {
            name: "MediRoute",
            tagline: "Reliable medical logistics when every minute matters",
            industry: "HealthTech",
            sub_industry: "Medical Logistics",
            founded_year: 2022,
            location: "Lucknow, India",
            website: "https://mediroute.example.com",
            description: "MediRoute coordinates time-sensitive medical deliveries between hospitals, laboratories and pharmacies.",
            problem: "Medical logistics is fragmented and delays can affect patient care.",
            solution: "Technology-enabled scheduling and tracking for medical deliveries.",
            business_model: "Transaction fees",
            target_market: "Hospitals, pharmacies and diagnostic labs",
            competitors: "Porter, Borzo",
            competitive_advantage: "Specialized workflows for healthcare deliveries.",
            stage: "Early Growth",
            team_size: 26,
            revenue: 7600000,
            monthly_revenue: 670000,
            revenue_growth: 28.7,
            customers: 280,
            active_users: 920,
            monthly_burn: 480000,
            runway: 19,
            gross_margin: 52,
            cac: 8500,
            ltv: 160000,
            funding_stage: "Seed",
            funding_required: 17000000,
            amount_raised: 8000000,
            valuation: 70000000,
            equity_offered: 14,
            minimum_investment: 500000
        }
    },
    {
        email: "nu1111zty@gmail.com",
        name: "HomeCraft",
        startup: {
            name: "HomeCraft",
            tagline: "Better homes through trusted local professionals",
            industry: "PropTech",
            sub_industry: "Home Services",
            founded_year: 2024,
            location: "Chandigarh, India",
            website: "https://homecraft.example.com",
            description: "HomeCraft connects homeowners with verified professionals for renovation, repair and interior projects.",
            problem: "Homeowners find it difficult to identify reliable professionals and compare quotations.",
            solution: "Verified professional marketplace with transparent project management.",
            business_model: "Marketplace commission",
            target_market: "Homeowners and renovation professionals",
            competitors: "Urban Company, Livspace",
            competitive_advantage: "End-to-end project tracking and verified contractors.",
            stage: "MVP",
            team_size: 15,
            revenue: 2300000,
            monthly_revenue: 210000,
            revenue_growth: 34.8,
            customers: 160,
            active_users: 720,
            monthly_burn: 240000,
            runway: 14,
            gross_margin: 41,
            cac: 4200,
            ltv: 68000,
            funding_stage: "Pre-Seed",
            funding_required: 9000000,
            amount_raised: 2200000,
            valuation: 36000000,
            equity_offered: 17,
            minimum_investment: 300000
        }
    },
    {
        email: "Its.sagar.here.03@gmail.com",
        name: "FleetZen",
        startup: {
            name: "FleetZen",
            tagline: "Simplifying vehicle operations",
            industry: "Mobility",
            sub_industry: "Fleet Technology",
            founded_year: 2022,
            location: "Pune, India",
            website: "https://fleetzen.example.com",
            description: "FleetZen provides fleet operators with vehicle maintenance, fuel and driver management tools.",
            problem: "Fleet operators spend significant time managing maintenance and operational records manually.",
            solution: "Centralized fleet operations software with automated reminders and analytics.",
            business_model: "B2B SaaS",
            target_market: "Transport companies and corporate fleets",
            competitors: "Fleetx, LocoNav",
            competitive_advantage: "Simple workflow focused on maintenance and operational efficiency.",
            stage: "Growth",
            team_size: 21,
            revenue: 5900000,
            monthly_revenue: 510000,
            revenue_growth: 25.1,
            customers: 430,
            active_users: 1700,
            monthly_burn: 360000,
            runway: 22,
            gross_margin: 77,
            cac: 6200,
            ltv: 132000,
            funding_stage: "Seed",
            funding_required: 15000000,
            amount_raised: 6500000,
            valuation: 62000000,
            equity_offered: 13,
            minimum_investment: 500000
        }
    },
    {
        email: "Sharma.sagar8988@gmail.com",
        name: "EduSphere",
        startup: {
            name: "EduSphere",
            tagline: "One learning platform for every learner",
            industry: "EdTech",
            sub_industry: "Learning Platform",
            founded_year: 2023,
            location: "Bhopal, India",
            website: "https://edusphere.example.com",
            description: "EduSphere provides personalized learning paths for students preparing for university and professional examinations.",
            problem: "Students struggle to identify what to study and how to measure their progress.",
            solution: "Adaptive learning paths with progress analytics and practice tests.",
            business_model: "Freemium subscription",
            target_market: "School and university students",
            competitors: "Physics Wallah, Unacademy, Vedantu",
            competitive_advantage: "Personalized study plans based on learner performance.",
            stage: "Early Growth",
            team_size: 23,
            revenue: 6400000,
            monthly_revenue: 570000,
            revenue_growth: 30.2,
            customers: 3100,
            active_users: 14200,
            monthly_burn: 430000,
            runway: 21,
            gross_margin: 74,
            cac: 1900,
            ltv: 42000,
            funding_stage: "Seed",
            funding_required: 13000000,
            amount_raised: 5200000,
            valuation: 52000000,
            equity_offered: 15,
            minimum_investment: 400000
        }
    },
    {
        email: "Sharmasagar9418@gmail.com",
        name: "FarmLink",
        startup: {
            name: "FarmLink",
            tagline: "Connecting farmers directly with buyers",
            industry: "AgriTech",
            sub_industry: "Agricultural Marketplace",
            founded_year: 2021,
            location: "Indore, India",
            website: "https://farmlink.example.com",
            description: "FarmLink connects farmers with institutional buyers and retailers while improving price transparency.",
            problem: "Farmers often have limited access to reliable buyers and transparent market prices.",
            solution: "Digital marketplace connecting producers directly with verified buyers.",
            business_model: "Transaction commission",
            target_market: "Farmers, retailers and food businesses",
            competitors: "DeHaat, Ninjacart",
            competitive_advantage: "Direct buyer relationships and transparent pricing.",
            stage: "Growth",
            team_size: 45,
            revenue: 20500000,
            monthly_revenue: 1780000,
            revenue_growth: 17.9,
            customers: 1850,
            active_users: 5400,
            monthly_burn: 980000,
            runway: 25,
            gross_margin: 31,
            cac: 4100,
            ltv: 94000,
            funding_stage: "Series A",
            funding_required: 55000000,
            amount_raised: 30000000,
            valuation: 240000000,
            equity_offered: 11,
            minimum_investment: 2500000
        }
    }
];

async function seed() {
    const client = await pool.connect();

    try {
        await client.query("BEGIN");

        console.log(`\nStarting seed for ${startups.length} startup accounts...\n`);

        for (const item of startups) {
            const existing = await client.query(
                "SELECT id FROM users WHERE LOWER(email) = LOWER($1)",
                [item.email]
            );

            if (existing.rows.length > 0) {
                console.log(`SKIPPED: ${item.email} already exists`);
                continue;
            }

            const hashedPassword = await bcrypt.hash(PASSWORD, 10);

            const userResult = await client.query(
                `
                INSERT INTO users (name, email, password, role)
                VALUES ($1, $2, $3, 'startup')
                RETURNING id
                `,
                [
                    item.name,
                    item.email,
                    hashedPassword
                ]
            );

            const founderId = userResult.rows[0].id;
            const s = item.startup;

            await client.query(
                `
                INSERT INTO startups (
                    founder_id,
                    name,
                    logo,
                    tagline,
                    industry,
                    sub_industry,
                    founded_year,
                    location,
                    website,
                    description,
                    problem,
                    solution,
                    business_model,
                    target_market,
                    competitors,
                    competitive_advantage,
                    stage,
                    team_size,
                    revenue,
                    monthly_revenue,
                    revenue_growth,
                    customers,
                    active_users,
                    monthly_burn,
                    runway,
                    gross_margin,
                    cac,
                    ltv,
                    funding_stage,
                    funding_required,
                    amount_raised,
                    valuation,
                    equity_offered,
                    minimum_investment,
                    status
                )
                VALUES (
                    $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
                    $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
                    $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
                    $31,$32,$33,$34,'PUBLISHED'
                )
                `,
                [
                    founderId,
                    s.name,
                    "",
                    s.tagline,
                    s.industry,
                    s.sub_industry,
                    s.founded_year,
                    s.location,
                    s.website,
                    s.description,
                    s.problem,
                    s.solution,
                    s.business_model,
                    s.target_market,
                    s.competitors,
                    s.competitive_advantage,
                    s.stage,
                    s.team_size,
                    s.revenue,
                    s.monthly_revenue,
                    s.revenue_growth,
                    s.customers,
                    s.active_users,
                    s.monthly_burn,
                    s.runway,
                    s.gross_margin,
                    s.cac,
                    s.ltv,
                    s.funding_stage,
                    s.funding_required,
                    s.amount_raised,
                    s.valuation,
                    s.equity_offered,
                    s.minimum_investment
                ]
            );

            console.log(`CREATED: ${item.email} → ${s.name}`);
        }

        await client.query("COMMIT");

        const countResult = await client.query(`
            SELECT COUNT(*) AS total
            FROM startups
            WHERE status = 'PUBLISHED'
        `);

        console.log("\n====================================");
        console.log("SEED COMPLETED SUCCESSFULLY");
        console.log("Published startups:", countResult.rows[0].total);
        console.log("Password for new accounts:", PASSWORD);
        console.log("====================================\n");

    } catch (error) {
        await client.query("ROLLBACK");

        console.error("\nSEED FAILED");
        console.error(error.message);
        console.error("\nNo partial changes were kept.");
    } finally {
        client.release();
        await pool.end();
    }
}

seed();